apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome
  labels:
    app: selenium-chrome
spec:
  type: ClusterIP
  ports:
  - port: 4444
    targetPort: 4444
    protocol: TCP
    name: webdriver
  - port: 7900
    targetPort: 7900
    protocol: TCP
    name: vnc
  selector:
    app: selenium-chrome