apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome-node
  labels:
    app: selenium-chrome-node
spec:
  type: ClusterIP
  ports:
  - port: 5555
    targetPort: 5555
    protocol: TCP
    name: node
  - port: 7900
    targetPort: 7900
    protocol: TCP
    name: vnc
  selector:
    app: selenium-chrome-node
