apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  type: NodePort
  ports:
  - port: 4444
    targetPort: 4444
    nodePort: 30444
    name: webdriver
  - port: 4443
    targetPort: 4443
    nodePort: 30443
    name: https
  - port: 4442
    targetPort: 4442
    nodePort: 30442
    name: publish
---
apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome-node
spec:
  type: NodePort
  ports:
  - port: 5555
    targetPort: 5555
    nodePort: 30555
    name: node
  - port: 7900
    targetPort: 7900
    nodePort: 30900
    name: vnc
